export const TAG_LOG = "SOCKET";
export const TAG_LOG_ERROR = "SOCKET_ERROR";
export const TAG_EVENT = {
  REQUEST_JOIN_ROOM: "REQUEST_JOIN_ROOM",
  RESPONSE_JOIN_ROOM: "RESPONSE_JOIN_ROOM",

  REQUEST_LEAVE_ROOM: "REQUEST_LEAVE_ROOM",
  RESPONSE_LEAVE_ROOM: "RESPONSE_LEAVE_ROOM",

  REQUEST_CHANGE_STATUS_ROOM: "REQUEST_CHANGE_STATUS_ROOM",
  RESPONSE_CHANGE_STATUS_ROOM: "RESPONSE_CHANGE_STATUS_ROOM",

  // Shipper
  REQUEST_SHIPPER_CHANGE_COOR: "REQUEST_SHIPPER_CHANGE_COOR",
  RESPONSE_SHIPPER_CHANGE_COOR: "RESPONSE_SHIPPER_CHANGE_COOR",

  REQUEST_SHIPPER_CONFIRM_ORDER: "REQUEST_SHIPPER_CONFIRM_ORDER",
  RESPONSE_SHIPPER_CONFIRM_ORDER: "RESPONSE_SHIPPER_CONFIRM_ORDER",

  // Merchant
  REQUEST_MERCHANT_CONFIRM_ORDER: "REQUEST_MERCHANT_CONFIRM_ORDER",
  RESPONSE_MERCHANT_CONFIRM_ORDER: "RESPONSE_MERCHANT_CONFIRM_ORDER",

  // Customer
};
