version: '3'
services:
  rest-server-datn:
    container_name: rest-server-datn
    image: paopaophan/rest-server-datn:latest
    restart: always
    build: ../
    ports:
      - '8000:8000'
    depends_on:
      - mongo

  mongo:
    container_name: 'mongo'
    image: 'mongo'
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27018'
