version: '3'
services:
  rest-server-datn:
    container_name: rest-server-datn
    image: paopaophan/rest-server-datn:latest
    restart: always
    build: ../
    ports:
      - '8000:8000'
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    container_name: 'mongo'
    image: 'mongo'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
